version: '3.8'
services:
    database:
        image: postgres
        restart: always
        env_file: .env
        networks:
            - back_net
            - bridge_net
        volumes:
            - ./db/postgresql:/var/lib/postgresql
        ports:
            - "5432:5432"
#    keycloak:
#        build: 
#            context: ./
#            dockerfile: Dockerfile
#        restart: always
#        environment:
#          KEYCLOAK_USER: admin
#          KEYCLOAK_ADMIN: admin
#          KEYCLOAK_PASSWORD: admin
#          KEYCLOAK_ADMIN_PASSWORD: admin
#          KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
#        command: start-dev
#        volumes:
#          - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
#        ports:
#          - "8180:8080"
networks:
    back_net:
        external: false
    bridge_net:
        driver: bridge